# config/application.yml

# Database
db_host: "localhost"
db_port: "5432"
db_name: ""
db_username: "postgres"
db_password: ""

# HackerNews
hacker_news_url: "https://hacker-news.firebaseio.com/"

# Redis
redis_host: "127.0.0.1"
redis_port: "6379"
redis_url: ""
